apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "redis-cluster.fullname" . }}
  labels:
    app: {{ include "redis-cluster.fullname" . }}
    {{- include "redis-cluster.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "redis-cluster.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "redis-cluster.fullname" . }}
      {{- include "redis-cluster.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "redis-cluster.fullname" . }}
        {{- include "redis-cluster.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "redis-cluster.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: client
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: gossip
              containerPort: {{ .Values.service.gossipPort }}
              protocol: TCP
          command: ["/conf/update-node.sh", "redis-server", "/conf/redis.conf"]
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          volumeMounts:
          - name: conf
            mountPath: /conf
            readOnly: false
          - name: data
            mountPath: /data
            readOnly: false
      volumes:
      - name: conf
        configMap:
          name: {{ include "redis-cluster.fullname" . }}
          defaultMode: 0755

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
